### ISSUE TITLE
Access to the unauthorized zone

### ISSUE THREAD

**Issue by rsilvestre** [JohnPhoto/JulmustRacet#1]
Hi,

I have access to https://julmustracet.se/add that supposed to be a secured zone. How did you explain than the authenticated layout don't redirect me to "/auth/signin" during the event "willTransitionTo"?

Regards

**Comment by JohnPhoto** [comment]
Will have to look into that.

**Comment by JohnPhoto** [comment]
Seems to work now.

**Comment by rsilvestre** [comment]
I also notice than you started to implement redux, are you going to continue that process?

**Comment by JohnPhoto** [comment]
We will see, that's the plan but I am not sure when the work will continue. Since the JulmustRace is only active in December each year I do not know how much I will maintain it due to other obligations at the moment.
